name: sales_volume_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alembic=1.9.1
  - altair=4.2.0
  - anyio=3.6.2
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - async_generator=1.10
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=5.0.1
  - blinker=1.5
  - blosc=1.21.3
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.6.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.2.0
  - certifi=2024.8.30
  - certipy=0.1.3
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.3.4
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - comm=0.1.2
  - conda-pack=0.8.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - configurable-http-proxy=4.5.3
  - contourpy=1.0.6
  - cryptography=39.0.0
  - cycler=0.11.0
  - cython=0.29.32
  - cytoolz=0.12.0
  - dask=2022.12.1
  - dask-core=2022.12.1
  - dav1d=1.0.0
  - debugpy=1.6.4
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - distributed=2022.12.1
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - executing=1.2.0
  - flatbuffers=2.0.8
  - flit-core=3.8.0
  - fmt=9.1.0
  - fonttools=4.38.0
  - fredapi=0.4.2
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - gast=0.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.15.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - greenlet=2.0.1
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - h5py=3.7.0
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.4
  - imagecodecs=2022.12.24
  - imageio=2.23.0
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - ipykernel=6.19.4
  - ipympl=0.9.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=7.4.8
  - jupyter_core=5.1.2
  - jupyter_events=0.5.0
  - jupyter_server=2.0.6
  - jupyter_server_terminals=0.4.3
  - jupyter_telemetry=0.1.0
  - jupyterhub=3.1.0
  - jupyterhub-base=3.1.0
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.18.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libmamba=1.1.0
  - libmambapy=1.1.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=15.0.6
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.2.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.2.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - msgpack-python=1.0.4
  - multidict=6.0.4
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbconvert=7.2.7
  - nbconvert-core=7.2.7
  - nbconvert-pandoc=7.2.7
  - nbformat=5.7.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.8.8
  - nodejs=18.12.1
  - nomkl=1.0
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numba=0.56.4
  - numexpr=2.8.3
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openblas=0.3.21
  - openjpeg=2.5.0
  - openpyxl=3.0.10
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=22.0
  - pamela=1.0.0
  - pandas=1.5.2
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - pluggy=1.0.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - protobuf=4.21.12
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pycurl=7.45.1
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=22.12.6
  - python-json-logger=2.0.4
  - python_abi=3.10
  - pytz=2022.7
  - pyu2f=0.1.5
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=24.0.1
  - re2=2022.06.01
  - readline=8.1.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scikit-image=0.19.3
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.46
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tblib=1.7.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.1
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tifffile=2022.10.10
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.8.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - werkzeug=2.2.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - wrapt=1.14.1
  - xlrd=2.0.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.8.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zlib-ng=2.0.6
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - adjusttext==0.8
      - alpha-vantage==2.3.1
      - appdirs==1.4.4
      - aquirdturtle-collapsible-headings==3.1.0
      - arrow==1.2.3
      - bayesian-optimization==1.4.2
      - black==23.1.0
      - bracex==2.3.post1
      - category-encoders==2.6.0
      - colourmap==1.1.10
      - cvxpy==1.3.0
      - ecos==2.0.12
      - exceptiongroup==1.1.0
      - feature-engine==1.5.2
      - fqdn==1.5.1
      - frozendict==2.3.5
      - gym==0.26.2
      - gym-notices==0.0.8
      - html5lib==1.1
      - imbalanced-learn==0.10.1
      - iniconfig==2.0.0
      - isoduration==20.11.0
      - jsonpointer==2.3
      - jupyterlab-spellchecker==0.7.3
      - keras-tuner==1.3.0
      - kt-legacy==1.0.4
      - lxml==4.9.2
      - mitdeeplearning==0.3.0
      - mlxtend==0.21.0
      - multitasking==0.0.11
      - mypy-extensions==1.0.0
      - nbclient==0.6.8
      - nbmake==1.4.1
      - nbqa==1.6.3
      - nnv==0.0.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - opencv-python==4.7.0.72
      - optbinning==0.17.3
      - ortools==9.5.2237
      - osqp==0.6.2.post8
      - pandas-datareader==0.10.0
      - pathspec==0.11.0
      - pca==1.9.1
      - plotly==5.13.1
      - pyaml==24.9.0
      - pydantic==1.10.5
      - pyspelling==2.7.2
      - pytest==7.2.2
      - python-graphviz==0.20.3
      - pytorch-tabnet==4.1.0
      - pyts==0.12.0
      - qdldl==0.1.5.post3
      - regex==2022.10.31
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - ropwr==1.0.0
      - scatterd==1.2.5
      - scikit-optimize==0.10.2
      - scs==3.2.2
      - setuptools==64.0.2
      - tenacity==8.2.2
      - tokenize-rt==5.0.0
      - torch==1.13.1
      - ucimlrepo==0.0.7
      - uri-template==1.2.0
      - wcmatch==8.4.1
      - webcolors==1.12
      - wget==3.2
      - wqet-grader==0.1.25
      - xgboost==1.7.4
      - yfinance==0.2.12
